const assetsData = {
  "background": [
    "bushland.png",
    "mountain.png",
    "nagano.png",
    "poppyfield.png",
    "roadside.png",
    "sonora.png",
    "sunrise.png",
    "sunset.png",
    "tennis.png",
    "wyoming.png"
  ],
  "wear": [
    "adida.png",
    "algorithm.png",
    "baby tee.png",
    "bear-shirt.png",
    "black-metamask.png",
    "btc.png",
    "cute-punk-rock.png",
    "eth.png",
    "ford.png",
    "gm.png",
    "hpos10i.png",
    "hunter-moggin.png",
    "internet-is-a-feeling.png",
    "miladypuppet_0053_xbox.png",
    "miladypuppet_0054_xbox.png",
    "mog-cat.png",
    "overs.png",
    "pepe.png",
    "playstation.png",
    "prep.png",
    "rad-bro-shirt.png",
    "remilio-redact-babies.png",
    "s&p6900.png",
    "solana.png",
    "tux.png",
    "white-metamask.png",
    "white-shirt.png",
    "xbox.png"
  ],
  "hair": [
    "black-bowl.png",
    "blonde-bowl.png",
    "blue-bowl.png",
    "harajuku-dye.png",
    "og-black.png",
    "og-blonde.png",
    "og-blue.png",
    "og-green.png",
    "og-orange.png",
    "pink-hair.png",
    "purple-bowl.png"
  ],
  "race": [
    "alien.png",
    "black.png",
    "clay.png",
    "pale.png",
    "pink.png",
    "tan.png"
  ],
  "eyes": [
    "classic-eyes.png",
    "heart-eyes.png",
    "mog.png",
    "sleepy-eyes.png",
    "smug-eyes.png",
    "spiral-eyes.png",
    "star-eyes.png",
    "tear-eyes.png"
  ],
  "costume": [
    "bear-suit.png",
    "frog-suit.png",
    "pika-suit.png",
    "red-niqab.png",
    "white-niqab.png"
  ],
  "headwear": [
    "creep.png",
    "deadape.png",
    "kirbro.png",
    "megumin.png",
    "shark-hat.png",
    "strawb-hat.png"
  ],
  "carry": [
    "ak.png",
    "bitcoin-bag.png",
    "bong.png",
    "cafeends-cup.png",
    "check.png",
    "controller.png",
    "dancing baby.png",
    "eth-bag.png",
    "gameboy.png",
    "hot-dog.png",
    "mac.png",
    "mature.png",
    "miladypuppet_0000_pickaxe.png",
    "miladypuppet_0001_blue-album.png",
    "miladypuppet_0007_btc-puppet.png",
    "miladypuppet_0008_remilia-eth-puppet.png",
    "miladypuppet_0009_strawb-radcat.png",
    "miladypuppet_0010_rad-cat.png",
    "miladypuppet_0011_kirbcat.png",
    "miladypuppet_0012_inversebrah.png",
    "miladypuppet_0013_pudgy-doll.png",
    "monster.png",
    "pitchfork.png",
    "pizza.png",
    "poppy.png",
    "rad-cat.png",
    "rpg.png",
    "s&p-token.png",
    "shovel.png",
    "spatula.png",
    "staff.png",
    "wii-remote.png",
    "wine.png"
  ]
};

export default assetsData;